workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - name: release
          keystore: $CM_KEYSTORE
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
          type: generic
          source: env
      vars:
        PACKAGE_NAME: "com.jotter.app"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
