workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference: keystore
          keystore:
            path: /tmp/keystore.keystore
            password: $KEYSTORE_PASSWORD
            key_alias: $KEY_ALIAS
            key_password: $KEY_PASSWORD
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.jotter.app"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
